version: '3.2'

services:

  mysql-db:
    image: mysql/mysql-server:8.0-dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tasd
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=db_micro
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - type: volume
        source: my-vol
        target: /var/lib/mysql
        volume:
          nocopy: true
    networks:
      - my-net
    deploy:
      placement:
        constraints:
          - node.role == manager
  micro2:
    image: miciav/micro:0.2
    restart: always
    environment:
      - MYSQL_ADDRESS=mysql-db
      - MYSQL_PORT=3306
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    networks:
      - my-net
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
      restart_policy:
        condition: on-failure

networks:
  my-net:
    driver: overlay

volumes:
  my-vol:
